title = "channels"

testid = 0

msgnum = -1
rate = 100
gap = 1000
nsqlookupds = ["nsq01.fulong.top:4161","nsq02.fulong.top:4161","nsq03.fulong.top:4161"]
runid = [230]
qlen = 20
listen = "0.0.0.0:7890"
threshold = 80
maxchannels = 3
fakegateway = 0 #模拟网关

[hbtime]
    timeout = 60
    delay = 10
    retry = 3

[mysql]
    user = "root"
    passwd = "e4ZZH7JMgh9e"
    host = "mysql01.fulong.top:3306"

[redis]
    host = "redis01.fulong.top:6379"
    user = ""
    passwd = "fulong@2021"
    db = "0"
    key = "index:account:infos:cmppaccounts"

[topicprefix]
    submit = "nsq.sms_push.submit."
    deliver = "nsq.sms_push.deliver."
    submit_resp = "nsq.sms_push.submit_resp."
    deliver_mo = "nsq.sms_push.deliver_mo."
    deliver_send = "nsq.sms_gateway.deliver."
    deliver_mo_send = "nsq.sms_gateway.deliver_mo."

[logconf]
    consoleloggingenabled = true
    encodeLogsasjson = false
    fileLoggingenabled = true
    directory = "/data/logs/"
    filename = "sms_gateway.log"
    maxsize = 10
    maxbackups = 10
    maxage = 10
    localtime = true
    compress = false
